// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
	"time"
)

type Contribution struct {
	ID         int32          `json:"id"`
	DepositID  sql.NullInt32  `json:"deposit_id"`
	Amount     int64          `json:"amount"`
	Currency   sql.NullString `json:"currency"`
	MemberID   int32          `json:"member_id"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	StatusCode string         `json:"status_code"`
}

type Deposit struct {
	ID           int32          `json:"id"`
	ReferenceNum string         `json:"reference_num"`
	Amount       int64          `json:"amount"`
	Currency     sql.NullString `json:"currency"`
	MemberID     int32          `json:"member_id"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	StatusCode   string         `json:"status_code"`
}

type Member struct {
	ID                int32        `json:"id"`
	FullName          string       `json:"full_name"`
	Email             string       `json:"email"`
	HashedPassword    string       `json:"hashed_password"`
	PasswordChangedAt time.Time    `json:"password_changed_at"`
	CreatedAt         sql.NullTime `json:"created_at"`
	StatusCode        string       `json:"status_code"`
}

type Status struct {
	Code      string       `json:"code"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}
