// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateContribution(ctx context.Context, arg CreateContributionParams) (Contribution, error)
	CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error)
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	CreateStatus(ctx context.Context, arg CreateStatusParams) (Status, error)
	DeleteContribution(ctx context.Context, id int32) error
	DeleteDeposit(ctx context.Context, id int32) error
	DeleteMember(ctx context.Context, id int32) error
	DeleteStatus(ctx context.Context, code string) error
	GetContribution(ctx context.Context, id int32) (Contribution, error)
	GetDeposit(ctx context.Context, id int32) (Deposit, error)
	GetDepositByReferenceNum(ctx context.Context, referenceNum string) (Deposit, error)
	GetMember(ctx context.Context, id int32) (Member, error)
	GetMemberByEmail(ctx context.Context, email string) (Member, error)
	GetStatus(ctx context.Context, code string) (Status, error)
	ListContributions(ctx context.Context) ([]Contribution, error)
	ListContributionsByDeposit(ctx context.Context, depositID sql.NullInt32) ([]Contribution, error)
	ListContributionsByMember(ctx context.Context, memberID int32) ([]Contribution, error)
	ListContributionsPaginated(ctx context.Context, arg ListContributionsPaginatedParams) ([]Contribution, error)
	ListDeposits(ctx context.Context) ([]Deposit, error)
	ListDepositsByMember(ctx context.Context, memberID int32) ([]Deposit, error)
	ListDepositsPaginated(ctx context.Context, arg ListDepositsPaginatedParams) ([]Deposit, error)
	ListMembers(ctx context.Context) ([]Member, error)
	ListMembersPaginated(ctx context.Context, arg ListMembersPaginatedParams) ([]Member, error)
	ListStatuses(ctx context.Context) ([]Status, error)
	ListStatusesPaginated(ctx context.Context, arg ListStatusesPaginatedParams) ([]Status, error)
	UpdateContribution(ctx context.Context, arg UpdateContributionParams) (Contribution, error)
	UpdateContributionStaus(ctx context.Context, arg UpdateContributionStausParams) (Contribution, error)
	UpdateDeposit(ctx context.Context, arg UpdateDepositParams) (Deposit, error)
	UpdateDepositStaus(ctx context.Context, arg UpdateDepositStausParams) (Deposit, error)
	UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error)
	UpdateMemberStaus(ctx context.Context, arg UpdateMemberStausParams) (Member, error)
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) (Status, error)
}

var _ Querier = (*Queries)(nil)
